Repository Galbio/42-minishell, pull requests merged in 2025-04, with the labels that each got.

#108 Add heredocs
  Makefile
  include/minishell.h
  src/commands/execute_line.c
  src/minishell.c
  src/parsers/bquotes_handler.c
  src/parsers/split_separators.c
  src/parsers/splitters_utils.c
  src/redirections/heredoc/handle_heredoc.c
  src/redirections/heredoc/handle_heredoc_utils.c
  src/redirections/heredoc/heredoc_quote_parser.c
  src/redirections/heredoc/parse_heredocs.c
  src/redirections/redirect_stdin.c
Labels: enhancement, redirections

#115 Add variable methods
  Makefile
  include/minishell.h
  src/argv/argv_utils.c
  src/argv/var_parser.c
  src/commands/execute_subcmd.c
  src/commands/execute_subshell.c
  src/parsers/split_separators.c
  src/utils/get_subcmd.c
  src/utils/var_names_utils.c
Labels: enhancement, parsing

#116 Add local variables support
  Makefile
  include/minishell.h
  src/argv/create_argv.c
  src/argv/local_var_handling.c
  src/argv/var_parser.c
  src/builtins/cd.c
  src/builtins/env.c
  src/builtins/export.c
  src/builtins/export_no_args.c
  src/builtins/unset.c
  src/commands/execute_subcmd.c
  src/envp/create_envp_cpy.c
  src/envp/parser.c
Labels: enhancement, parsing, builtins

#124 Fix redirections with multi file
  include/minishell.h
  src/argv/create_argv.c
  src/commands/execute_bin.c
  src/redirections/add_redir_argv.c
  src/redirections/redirect_stdin.c
  src/redirections/redirect_stdout.c
  src/utils/free_cmd.c
Labels: bug, redirections

#125 Subshell in env builtin
  include/minishell.h
  src/builtins/env.c
  src/commands/execute_bin.c
  src/commands/execute_command.c
Labels: enhancement, builtins

#126 Add an error parsing
  include/minishell.h
  src/commands/execute_line.c
  src/parsers/split_separators.c
  src/parsers/splitters_utils.c
Labels: parsing

#129 Fix exit message position
  src/ft_readline/events/default/interrupt.c
  src/minishell.c
Labels: bug, readline

#132 Auto completion system
  Makefile
  include/ft_readline.h
  include/ft_readline_keys.h
  src/ft_readline/autocompletion/commands.c
  src/ft_readline/autocompletion/display.c
  src/ft_readline/autocompletion/research.c
  src/ft_readline/autocompletion/utils.c
  src/ft_readline/autocompletion/variables.c
  src/ft_readline/cursor/position/stdin.c
  src/ft_readline/events/default/autocompletion.c
  src/ft_readline/events/default_events.c
  src/ft_readline/exit.c
  src/ft_readline/extra/env.c
  src/ft_readline/extra/env/envp.c
  src/ft_readline/extra/env/path.c
  src/ft_readline/extra/size.c
  src/ft_readline/initialization.c
  src/ft_readline/process/converter.c
  src/ft_readline/process/handler.c
  src/minishell.c
Labels: enhancement, readline

#130 Brace Variable Expansion
  Makefile
  include/minishell.h
  src/argv/braces/expansion.c
  src/argv/braces/methods.c
  src/argv/var_parser.c
  src/signals/exit_status.c
Labels: enhancement

#137 Fix Multi Tabs
  src/ft_readline/autocompletion/display.c
Labels: bug, readline

#138 Add similar commands support
  Makefile
  include/minishell.h
  src/builtins/alias.c
  src/builtins/cd.c
  src/builtins/exit.c
  src/builtins/export.c
  src/commands/execute_bin.c
  src/commands/similar_commands.c
  src/redirections/heredoc/handle_heredoc_utils.c
  src/utils/display_errors.c
Labels: enhancement

#139 Add Files and Directories Autocompletions
  Makefile
  include/ft_readline.h
  src/ft_readline/autocompletion/files_and_dirs.c
  src/ft_readline/autocompletion/research.c
  src/ft_readline/autocompletion/utils.c
  src/ft_readline/events/default/autocompletion.c
Labels: enhancement, readline

#136 Add Dynamic Prompt
  Makefile
  include/minishell.h
  src/argv/local_var_handling.c
  src/builtins/change_pwd.c
  src/builtins/export.c
  src/builtins/unset.c
  src/envp/parser.c
  src/envp/path.c
  src/envp/update.c
  src/ft_readline/char/position.c
  src/ft_readline/edition/utils.c
  src/ft_readline/edition/write.c
  src/ft_readline/events/default/history.c
  src/ft_readline/format/lines_count.c
  src/ft_readline/initialization.c
  src/minishell.c
  src/prompt.c
  src/utils/free_cmd.c
Labels: enhancement

#140 Fix exit message fd
  src/minishell.c
Labels: bug

#141 Yet another error pr
  src/commands/execute_bin.c
  src/parsers/split_separators.c
  src/parsers/splitters_utils.c
Labels: bug

#142 Fix Minishell in a pipe
  include/ft_readline.h
  src/ft_readline/events/default/breakline.c
  src/ft_readline/ft_readline.c
  src/ft_readline/initialization.c
  src/ft_readline/process/reader.c
  src/main.c
  src/minishell.c
Labels: bug

#143 Fix variable bugs
  include/minishell.h
  src/argv/argv_utils.c
  src/argv/local_var_handling.c
  src/argv/parse_cmd_return.c
  src/argv/var_parser.c
  src/commands/execute_subcmd.c
Labels: bug, parsing

#144 Fix redir bug pipe
  src/redirections/redirect_stdin.c
Labels: bug, redirections

#145 Fix exits codes and some things
  src/builtins/cd.c
  src/builtins/exit.c
  src/ft_readline/process/converter.c
Labels: bug

#146 Fix var and shlvl bug
  include/minishell.h
  src/argv/var_parser.c
  src/main.c
  src/minishell.c
Labels: bug

#147 Fix if is a dir
  src/commands/execute_bin.c
Labels: bug

#151 Fix pipe error
  src/parsers/split_separators.c
Labels: bug

#150 Fix empty var and other stuff
  include/minishell.h
  src/argv/argv_utils.c
  src/argv/create_argv.c
  src/argv/local_var_handling.c
  src/argv/var_parser.c
  src/commands/execute_bin.c
  src/commands/execute_command.c
Labels: bug

#152 Fix some bugs
  include/minishell.h
  src/argv/create_argv.c
  src/commands/execute_command.c
  src/envp/parser.c
  src/minishell.c
  src/parsers/split_separators.c
  src/redirections/add_redir_argv.c
  src/redirections/heredoc/handle_heredoc.c
  src/redirections/heredoc/handle_heredoc_utils.c
  src/utils/display_errors.c
Labels: bug

#154 Yet another bug pr
  include/minishell.h
  src/commands/execute_command.c
  src/parsers/split_separators.c
  src/parsers/splitters_utils.c
  src/redirections/add_redir_argv.c
  src/redirections/heredoc/handle_heredoc_utils.c
  src/utils/display_errors.c
Labels: bug

#155 Add pretty Makefile
  Makefile
Labels: enhancement

#156 Fix/pipe exit code
  include/minishell.h
  src/commands/execute_command.c
  src/parsers/split_separators.c
  src/parsers/splitters_utils.c
Labels: bug

#157 Fix exit builtins bugs
  src/builtins/cd.c
  src/builtins/exit.c
Labels: bug, builtins

#158 I love errors
  Makefile
  include/minishell.h
  src/argv/add_splitted.c
  src/argv/var_parser.c
  src/builtins/env.c
  src/commands/execute_bin.c
  src/redirections/add_redir_argv.c
  src/redirections/errors.c
  src/utils/get_subcmd.c
  src/utils/handle_var_quote.c
  src/utils/parse_anti_wildcard.c
Labels: bug

#159 Fix Somes Syntaxes
  include/minishell.h
  src/commands/execute_command.c
  src/parsers/splitters_utils.c
  src/redirections/heredoc/handle_heredoc_utils.c
  src/utils/token_errors.c
Labels: bug

#160 .
  src/commands/execute_bin.c
Labels: point
