Repository Galbio/42-minishell, pull requests merged in 2025-02, with the labels that each got.

#1 Add Makefile
  Makefile
Labels: compilation

#3 Fix include
  include/minishell.h
Labels: bug

#4 quote parsing function
  include/minishell.h
  src/quote_parser.c
Labels: parsing

#16 Fix Project
  Makefile
  include/minishell.h
  src/build_in.c
  src/commands/create_argv.c
  src/quote_parser.c
Labels: bug, compilation

#17 Fix Cursor Usage
  .gitmodules
  Makefile
  include/minishell.h
  include/readline.h
  src/readline/clean_readed.c
  src/utils/ft_is_quote.c
  src/utils/ft_is_whitespace.c
  src/utils/ft_readline.c
  src/utils/ft_realloc.c
  src/utils/ft_securejoin.c
  src/utils/ft_securelen.c
  src/utils/get_next_line.c
Labels: bug
